name: Release

on:
  push:
    tags:
      - 'v*'   # se ejecuta cuando haces git tag v1.0.0

permissions:
  contents: write

jobs:
  make:
    name: Make on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      # Necesario para maker-zip en Linux
      - name: Install zip (Linux only)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Make distributables
        run: npm run make
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Releases
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}